version: '3.5'

services:
  web:
    container_name: address-web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './src:/src/app'
    command: npm run start
    networks:
      - webnet
    environment:
      PORT: 3000
    depends_on:
      - postgres

  nginx:
    container_name: address-nginx
    restart: always
    build: ./nginx/
    ports:
      - '8080:80'
    volumes:
      - /www/public
    links:
      - web
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: address-postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:
volumes:
  pgdata:
