version: '3.5'

services:

    web:
        container_name: gateway-user-web
        build:
            context: ./
            dockerfile: Dockerfile
        volumes: 
            "./src:/usr/src/app"
        command: npm start
        # networks: 
        environment: 
            PORT: 3000
    
    nginx:
        container_name: gateway-user-nginx
        restart: always
        build: ./nginx/
        ports: 
            - "80:3000"
        volumes:
            - /www/public
        # networks: 