version: '3.5'

services:

    web:
        container_name: gateway-user-web
        build:
            context: ./
            dockerfile: Dockerfile
        volumes: 
            - "./src:/src/app"
        command: npm run start
        environment: 
            PORT: 3000
    
    nginx:
        container_name: gateway-user-nginx
        restart: always
        build: ./nginx/
        ports: 
            - "80:80"
        volumes:
            - /www/public
        links:
            - web