version: '3.5'

services:

    web:
        container_name: gateway-user-web
        build:
            context: ./
            dockerfile: Dockerfile
        networks: 
            - autenticacao
        volumes: 
            - "./src:/src/app"
        command: npm run start
        environment: 
            PORT: 3000
            AUTH: http://authentication-api
    
    nginx:
        container_name: gateway-user-nginx
        restart: always
        build: ./nginx/
        ports: 
            - "80:80"
        volumes:
            - /www/public
        links:
            - web

networks: 

    food-bridge:
        name: food_gatework_network
        driver: bridge
    autenticacao:
        external:
            name: authentication-network