version: '3.5'

services:

  web:
    container_name: empresa-food-deno
    working_dir: /usr/src/app
    environment:
      MONGODB_URL: mongo
      MONGODB_USER: root
      MONGODB_PASS: password
    build:
      args:
        PORT: 3000
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./src:/usr/src/app"
    command: bash -c "deno run --allow-net --allow-env --allow-read index.ts"
    networks:
      - empresa-food-network
    links:
      - mongo

  mongo:
    image: mongo
    container_name: empresa-food-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    networks:
      - empresa-food-network

networks:
    empresa-food-network:
      driver: bridge