version: '3.5'

services:
  api:
    container_name: account-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/src/app'
    command: npm run start
    environment:
      PORT: 3000
    networks:
      - account-network

  database:
    container_name: account-database
    image: mongo:4.2.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: C0op3r#2020
    ports:
      - '27017:27017'
    volumes:
      - ./database:/data/db
    networks:
      - account-network

networks:
  account-network:
    driver: bridge
