version: '3.0'

services:

  service-backend-database:
    user: root
    image: mcr.microsoft.com/mssql/server:latest
    container_name: database-mssql
    volumes:
      # - ./database/docker-data:/var/opt/mssql # for mac
      - ./database/docker-data:/var/opt/mssql # for linux
      # - var/opt/mssql/data # for mac
    ports:
      - "1433:1433"


  service-backend-server:
    image: tomcat
    user: root
    build:
      context: ./
      dockerfile: Dockerfile

    volumes:
      - /image_upload:/image_upload
      - ./target/empresa-api-0.0.1-SNAPSHOT.jar:/usr/local/tomcat/webapps/intercoop-api-0.0.1-SNAPSHOT.jar
    #ports:
    #  - "8080:8080"
    network_mode: "host"
    environment:
      URL_BANCO: service-backend-database
      GATEWAY_URL: http://gateway-user-nginx
    networks:
      - default
      - gateway

networks:
  default:
    name: empresas-network
    driver: bridge
    #ipam:
    #  config:
    #    - subnet: 172.16.57.0/24
  gateway:
    external:
      name: food_gatework_network
