version: '3.1'

services:

  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: pedidos_usr
      POSTGRES_PASSWORD: pedidos_pass
      POSTGRES_DB: pedidos_db
    ports:
      - "5432:5432"