version: '3'

services:
  nest-api:
    build: .
    container_name: nest-api
    environment:
      - DB_HOST=postgres
      - GATEWAY_API=http://gateway_cotainer_nginx
    volumes:
      - .:/home/node/nestapi
      - /home/node/nestapi/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - gateway
    depends_on:
      - postgres
    command: >
      sh -c "npm run typeorm:migrate &&
              npm run start:prod"
    networks:
      - nestwork
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - nestwork
networks:
  nestwork:
    driver: bridge
  gateway:
    external:
      name: gateway_network