version: '3.5'

services:
  api:
    container_name: authentication-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/src/app'
    command: npm run start
    environment:
      PORT: 3000
    networks:
      - authentication-network

networks:
  authentication-network:
    driver: bridge
